const stickers = [
    // ===== ARGENTINA ===== //
    { id: 180, name: "Escudo Mate", price: 600, image: "/images/escudomate.png", available:true, category: "argentina" },
  { id: 80, name: "Sol Argentina", price: 600, image: "/images/solarg.png", available:true, category: "argentina" },
  { id: 172, name: "Banderita Arg", price: 600, image: "/images/banderitaarg.png", available:true, category: "argentina" },
  { id: 104, name: "Universidad Pública", price: 600, image: "/images/universidad.jpg", available:true, category: "argentina" },
  { id: 81, name: "Mate", price: 600, image: "/images/mate.png", available:true, category: "argentina" },
  { id: 149, name: "Mate + Termo", price: 600, image: "/images/matetermo.png", available:true, category: "argentina" },
  { id: 82, name: "Ruta 40", price: 600, image: "/images/arg.png", available:true, category: "argentina" },
  { id: 145, name: "Carpincho Matero", price: 600, image: "/images/carpincho matero.png", available:true, category: "argentina" },
  { id: 110, name: "25 de mayo", price: 600, image: "/images/25demayo.png", available:true, category: "argentina" },
  { id: 113, name: "CalMATE", price: 600, image: "/images/calmate.png", available:true, category: "argentina" },
  { id: 111, name: "Amargos como tu vida", price: 600, image: "/images/amargos.png", available:true, category: "argentina" },
  { id: 129, name: "Malvinas Argentinas", price: 600, image: "/images/malvinas.png", available:true, category: "argentina" },
  { id: 141, name: "Argentina", price: 600, image: "/images/argentina.png", available:true, category: "argentina" },
  { id: 125, name: "Homero Mate", price: 600, image: "/images/homeromate.png", available:true, category: "argentina" },
  { id: 155, name: "Fernet", price: 600, image: "/images/fernet.png", available:true, category: "argentina" },
  { id: 159, name: "Chipa Lover", price: 600, image: "/images/chipalover.png", available:true, category: "argentina" },
{ id: 180, name: "Vaso Fernet", price: 600, image: "/images/vasofernet.png", available:true, category: "argentina" },
  // ===== FÚTBOL ARGENTINO ===== //
  { id: 24, name: "Estampita Di María (5x8cm)", price: 650, image: "/images/estampita_dimaria.png", available:true, category: "futbol-argentino" },
  { id: 25, name: "Estampita Messi (5x8cm)", price: 650, image: "/images/estampita_messi.png", available:true, category: "futbol-argentino" },
  { id: 26, name: "Estampita Julián (5x8cm)", price: 650, image: "/images/julian.png", available:true, category: "futbol-argentino" },
  { id: 27, name: "Estampita Dibu (5x8cm)", price: 650, image: "/images/estampitadibu.png", available:true, category: "futbol-argentino" },
  { id: 121, name: "Estampita Scaloni", price: 650, image: "/images/estampitascaloni.png", available:true, category: "futbol-argentino" },
  { id: 174, name: "Scaloneta", price: 600, image: "/images/scaloneta.png", available:true, category: "futbol-argentino" },
  { id: 62, name: "Escudo CARP", price: 600, image: "/images/carp.png", available:true, category: "futbol-argentino" },
  { id: 144, name: "CARP", price: 600, image: "/images/carp2.png", available:true, category: "futbol-argentino" },
  { id: 63, name: "Roman 10", price: 600, image: "/images/roman.png", available:true, category: "futbol-argentino" },
  { id: 64, name: "Bombonera", price: 600, image: "/images/bombonera.png", available:true, category: "futbol-argentino" },
  { id: 69, name: "Escudo Central", price: 600, image: "/images/centralescudo.png", available:true, category: "futbol-argentino" },
  { id: 70, name: "Central Campeon", price: 600, image: "/images/campeon.png", available:true, category: "futbol-argentino" },
  { id: 71, name: "Soy Canaya", price: 600, image: "/images/canaya.png", available:true, category: "futbol-argentino" },
  { id: 72, name: "Escudo Nob", price: 600, image: "/images/nobescudo.png", available:true, category: "futbol-argentino" },
  { id: 73, name: "NOB", price: 600, image: "/images/nob.png", available:true, category: "futbol-argentino" },
  { id: 74, name: "Messi Newells", price: 550, image: "/images/messinob.png", available:true, category: "futbol-argentino" },
  { id: 75, name: "Messi Copa", price: 600, image: "/images/messicopa.png", available:true, category: "futbol-argentino" },
  { id: 76, name: "Messi Topo Gigio", price: 600, image: "/images/messi10.png", available:true, category: "futbol-argentino" },
  { id: 77, name: "AFA", price: 600, image: "/images/afa.png", available:true, category: "futbol-argentino" },
  { id: 78, name: "Estampita Diego", price: 600, image: "/images/diego.png", available:true, category: "futbol-argentino" },
  { id: 147, name: "Diego Mate", price: 600, image: "/images/diegomate.png", available:true, category: "futbol-argentino" },
  { id: 79, name: "Diego", price: 600, image: "/images/diego2.png", available:true, category: "futbol-argentino" },
  { id: 120, name: "Escudo boca", price: 600, image: "/images/escudoboca.png", available:true, category: "futbol-argentino" },
  { id: 115, name: "Campeones del mundo", price: 600, image: "/images/campeones.png", available:true, category: "futbol-argentino" },
  { id: 159, name: "Messi Copas Americas", price: 600, image: "/images/messicopaamerica.png", available:true, category: "futbol-argentino" },
  { id: 176, name: "Camiseta Di Maria", price: 600, image: "/images/camisetadimaria.png", available:true, category: "futbol-argentino" },
  { id: 178, name: "Di Maria Central", price: 600, image: "/images/angel.png", available:true, category: "futbol-argentino" },

  // ===== NATURALEZA ===== //
  { id: 12, name: "Mariposa", price: 600, image: "/images/mariposa.png", available:true, category: "naturaleza" },
  { id: 110, name: "Mariposa Azul", price: 600, image: "/images/mariposaazul.png", available:true, category: "naturaleza" },
  { id: 15, name: "Estampita Paisaje", price: 550, image: "/images/pasiaje1.png", available:true, category: "naturaleza" },
  { id: 39, name: "Flores rosas", price: 600, image: "/images/floores.png", available:true, category: "naturaleza" },
  { id: 40, name: "Ramo flores", price: 600, image: "/images/floress.png", available:true, category: "naturaleza" },
  { id: 41, name: "Flores Azules", price: 600, image: "/images/floresazules.png", available:true, category: "naturaleza" },
  { id: 42, name: "Arcoiris", price: 600, image: "/images/arcoiris.png", available:true, category: "naturaleza" },
  { id: 44, name: "Margarita", price: 600, image: "/images/margarita.png", available:true, category: "naturaleza" },
  { id: 53, name: "Tulipan", price: 500, image: "/images/tulipan.png", available:true, category: "naturaleza" },
  { id: 116, name: "Cerezas", price: 550, image: "/images/cerezas.png", available:true, category: "naturaleza" },
  { id: 122, name: "Flor Violeta", price: 600, image: "/images/florvioleta.png", available:true, category: "naturaleza" },
  { id: 136, name: "Solcito", price: 600, image: "/images/solcute.png", available:true, category: "naturaleza" },
  { id: 143, name: "Burbuja", price: 600, image: "/images/burbuja.png", available:true, category: "naturaleza" },
  { id: 152, name: "Paisaje Circular", price: 600, image: "/images/paisajecirculo.png", available:true, category: "naturaleza" },
  { id: 153, name: "Paisaje 2", price: 600, image: "/images/paipai.png", available:true, category: "naturaleza" },
  { id: 154, name: "Frutillita", price: 600, image: "/images/frutillita.png", available:true, category: "naturaleza" },
  { id: 163, name: "Corazon Verde", price: 600, image: "/images/corazonverde.png", available:true, category: "naturaleza" },
  { id: 164, name: "Almeja", price: 600, image: "/images/caracol.png", available:true, category: "naturaleza" },
  { id: 166, name: "Capibara", price: 600, image: "/images/capibara.png", available:true, category: "naturaleza" },
  { id: 167, name: "Faro", price: 550, image: "/images/faro.png", available:true, category: "naturaleza" },
  { id: 168, name: "Caracol", price: 600, image: "/images/caracol2.png", available:true, category: "naturaleza" },
  { id: 170, name: "Caracol 2", price: 600, image: "/images/caracol3.png", available:true, category: "naturaleza" },

  // ===== MÚSICA ARGENTINA ===== //
  { id: 20, name: "Spinetta Artaud", price: 550, image: "/images/artaud.png", available:true, category: "musica-argentina" },
  { id: 151, name: "Charly", price: 600, image: "/images/charlyREAL.png", available:true, category: "musica-argentina" },
  { id: 21, name: "Almendra", price: 550, image: "/images/almendra.png", available:true, category: "musica-argentina" },
  { id: 52, name: "Oscuro Extasis - Wos", price: 600, image: "/images/wos.png", available:true, category: "musica-argentina" },
  { id: 139, name: "Ysy A", price: 600, image: "/images/ysya.png", available:true, category: "musica-argentina" },
  { id: 171, name: "Tini", price: 550, image: "/images/tini.png", available:true, category: "musica-argentina" },
  { id: 180, name: "Un Poco De Ruido", price: 600, image: "/images/unpocoderuido.png", available:true, category: "argentina" },

  // ===== MÚSICA INTERNACIONAL ===== //
  { id: 1, name: "Un verano sin ti", price: 600, image: "/images/badbunny.png", available:true, category: "musica-internacional" },
  { id: 2, name: "DtMF - BadBunny", price: 550, image: "/images/dtmf.png", available:true, category: "musica-internacional" },
  { id: 3, name: "Daddy", price: 600, image: "/images/daddy.png", available:true, category: "musica-internacional" },
  { id: 45, name: "Tyler ID", price: 600, image: "/images/tylerid.png", available:true, category: "musica-internacional" },
  { id: 46, name: "MF DOOM", price: 600, image: "/images/mfdoom.png", available:true, category: "musica-internacional" },
  { id: 47, name: "DAMN - Kendrick", price: 500, image: "/images/damn.png", available:true, category: "musica-internacional" },
  { id: 48, name: "Chromakopia", price: 500, image: "/images/chromakopia.png", available:true, category: "musica-internacional" },
  { id: 51, name: "Here comes the sun", price: 600, image: "/images/sun.png", available:false, category: "musica-internacional" },
  { id: 93, name: "ACDC", price: 600, image: "/images/acdc.png", available:true, category: "musica-internacional" },
  { id: 94, name: "Bon Jovi", price: 600, image: "/images/bonjovi.png", available:true, category: "musica-internacional" },
  { id: 112, name: "Bowie", price: 600, image: "/images/bowie.png", available:true, category: "musica-internacional" },
  { id: 131, name: "Pink Floyd", price: 600, image: "/images/pinkfloyd.png", available:true, category: "musica-internacional" },
  { id: 137, name: "Travis Scott", price: 600, image: "/images/travis.png", available:true, category: "musica-internacional" },
  { id: 153, name: "Sour Olivia Rodrigo", price: 600, image: "/images/sour.png", available:true, category: "musica-internacional" },
  { id: 161, name: "Dancing Queen", price: 550, image: "/images/dancingqueen.png", available:true, category: "musica-internacional" },
  { id: 173, name: "Led Zeppelin", price: 600, image: "/images/led.png", available:true, category: "musica-internacional" },

  // ===== MARCAS DE ROPA/ESTILO ===== //
  { id: 83, name: "Logo Nike", price: 550, image: "/images/nike.png", available:true, category: "marcas-ropa" },
  { id: 102, name: "Coca Cola", price: 600, image: "/images/coca.png", available:true, category: "marcas-ropa" },
  { id: 103, name: "Malboro", price: 600, image: "/images/malboro.png", available:true, category: "marcas-ropa" },
  { id: 105, name: "Logo Vans", price: 500, image: "/images/logovans.png", available:true, category: "marcas-ropa" },
  { id: 106, name: "Zapatilla", price: 550, image: "/images/llanta.png", available:true, category: "marcas-ropa" },
  { id: 107, name: "Vans", price: 600, image: "/images/vans.png", available:true, category: "marcas-ropa" },
  { id: 108, name: "North Face", price: 600, image: "/images/northface.png", available:true, category: "marcas-ropa" },
  { id: 109, name: "DC", price: 600, image: "/images/dc.png", available:true, category: "marcas-ropa" },
  { id: 140, name: "Adidas", price: 600, image: "/images/adidas.png", available:true, category: "marcas-ropa" },
  { id: 151, name: "Santa Cruz Ola", price: 600, image: "/images/santacruzola.png", available:true, category: "marcas-ropa" },
  { id: 152, name: "Santa Cruz Verde", price: 600, image: "/images/santacruzverde.png", available:true, category: "marcas-ropa" },
  { id: 175, name: "Thrasher", price: 600, image: "/images/thrasherprueba.png", available:true, category: "marcas-ropa" },

  // ===== PELÍCULAS/SERIES ===== //
  { id: 4, name: "Fight Club", price: 550, image: "/images/fightclub.png", available:true, category: "peliculas-series" },
  { id: 55, name: "A Tim Burton Film", price: 600, image: "/images/timburton.png", available:true, category: "peliculas-series" },
  { id: 95, name: "Batman", price: 600, image: "/images/batman.png", available:true, category: "peliculas-series" },
  { id: 96, name: "Capitan America", price: 600, image: "/images/capitanamerica.png", available:true, category: "peliculas-series" },
  { id: 97, name: "Superman", price: 600, image: "/images/superman.png", available:true, category: "peliculas-series" },
  { id: 98, name: "Marvel", price: 600, image: "/images/marvel.png", available:true, category: "peliculas-series" },
  { id: 100, name: "Flash", price: 600, image: "/images/flash.png", available:true, category: "peliculas-series" },
  { id: 124, name: "Gelatina The Office", price: 600, image: "/images/gelatina.png", available:true, category: "peliculas-series" },
  { id: 158, name: "Tarantino", price: 600, image: "/images/tarantino.png", available:true, category: "peliculas-series" },
  { id: 179, name: "Chimuelo", price: 600, image: "/images/comoentrenaratu.png", available:true, category: "peliculas-series" },

  // ===== CARICATURAS/ANIMÉ ===== //
  { id: 6, name: "Pickle Rick", price: 600, image: "/images/rick.png", available:true, category: "caricaturas-anime" },
  { id: 29, name: "Garfield", price: 600, image: "/images/garfield.png", available:true, category: "caricaturas-anime" },
  { id: 33, name: "Winnie Pooh", price: 600, image: "/images/winniep.png", available:true, category: "caricaturas-anime" },
  { id: 50, name: "Snoopy", price: 600, image: "/images/snoopy.png", available:true, category: "caricaturas-anime" },
  { id: 54, name: "Tom", price: 600, image: "/images/tom.png", available:true, category: "caricaturas-anime" },
  { id: 60, name: "Stitch", price: 600, image: "/images/stich.png", available:true, category: "caricaturas-anime" },
  { id: 99, name: "Cartoon Network", price: 600, image: "/images/cartoon.png", available:true, category: "caricaturas-anime" },
  { id: 118, name: "Duff Beer", price: 600, image: "/images/duff.png", available:true, category: "caricaturas-anime" },
  { id: 119, name: "Escandalosos", price: 600, image: "/images/escandalosos.png", available:true, category: "caricaturas-anime" },
  { id: 123, name: "Gato coqueto", price: 600, image: "/images/gatopucho.png", available:true, category: "caricaturas-anime" },
  { id: 128, name: "Mafalda", price: 600, image: "/images/mafalda.png", available:true, category: "caricaturas-anime" },
  { id: 130, name: "Max Goofy", price: 600, image: "/images/maxgoofy.png", available:true, category: "caricaturas-anime" },
  { id: 156, name: "Monster University", price: 600, image: "/images/monsteru.png", available:true, category: "caricaturas-anime" },
  { id: 157, name: "Nube", price: 600, image: "/images/nubenaruto.png", available:true, category: "caricaturas-anime" },
  { id: 177, name: "Stitch Guitarra", price: 600, image: "/images/stitchguitarra.png", available:true, category: "caricaturas-anime" },
  { id: 179, name: "Lisa", price: 600, image: "/images/lisa.png", available:true, category: "caricaturas-anime" },

   // ===== ESTAMPITAS/MISCELÁNEOS ===== //
  { id: 5, name: "The World Is Yours", price: 500, image: "/images/globo.png", available:true, category: "miscelaneos" },
  { id: 7, name: "Classic Garage", price: 600, image: "/images/garage.png", available:true, category: "miscelaneos" },
  { id: 8, name: "Just A Girl", price: 500, image: "/images/girl.png", available:true, category: "miscelaneos" },
  { id: 9, name: "El Grito", price: 600, image: "/images/grito.png", available:true, category: "miscelaneos" },
  { id: 10, name: "Carta Lovers", price: 600, image: "/images/lovers.png", available:true, category: "miscelaneos" },
  { id: 11, name: "Luna Tarot", price: 600, image: "/images/luna.png", available:true, category: "miscelaneos" },
  { id: 13, name: "MTV", price: 600, image: "/images/mtv.png", available:true, category: "miscelaneos" },
  { id: 14, name: "Ola de Kanawa", price: 600, image: "/images/ola.png", available:true, category: "miscelaneos" },
  { id: 16, name: "Queen Cartas", price: 600, image: "/images/queen.png", available:true, category: "miscelaneos" },
  { id: 17, name: "Reader Carta", price: 600, image: "/images/reader.png", available:true, category: "miscelaneos" },
  { id: 18, name: "Sol Tarot", price: 600, image: "/images/sol.png", available:true, category: "miscelaneos" },
  { id: 19, name: "Treat People With Kindness", price: 600, image: "/images/tpwk.png", available:true, category: "miscelaneos" },
  { id: 22, name: "Dino", price: 600, image: "/images/dino.png", available:true, category: "miscelaneos" },
  { id: 28, name: "Fantasmita", price: 600, image: "/images/fantasmita.png", available:true, category: "miscelaneos" },
  { id: 30, name: "Good Days", price: 600, image: "/images/gooddays.png", available:true, category: "miscelaneos" },
  { id: 31, name: "Study!", price: 600, image: "/images/study.png", available:true, category: "miscelaneos" },
  { id: 32, name: "Alien", price: 600, image: "/images/alien.png", available:true, category: "miscelaneos" },
  { id: 34, name: "Ángel Caído", price: 600, image: "/images/angelcaido.png", available:true, category: "miscelaneos" },
  { id: 35, name: "Arpa", price: 600, image: "/images/arpa.png", available:true, category: "miscelaneos" },
  { id: 36, name: "Corazón", price: 600, image: "/images/corazon.png", available:true, category: "miscelaneos" },
  { id: 37, name: "Encendedor", price: 550, image: "/images/encendedor.png", available:true, category: "miscelaneos" },
  { id: 38, name: "Esqueleto en llamas", price: 600, image: "/images/esqueleto.png", available:true, category: "miscelaneos" },
  { id: 43, name: "Luna", price: 600, image: "/images/moon.png", available:true, category: "miscelaneos" },
  { id: 49, name: "Ojo Turco", price: 600, image: "/images/ojoturco.png", available:true, category: "miscelaneos" },
  { id: 56, name: "This is fine", price: 600, image: "/images/thisisfine.png", available:true, category: "miscelaneos" },
  { id: 57, name: "Telephone", price: 600, image: "/images/telefono.png", available:true, category: "miscelaneos" },
  { id: 58, name: "Tabla surf", price: 500, image: "/images/surf.png", available:true, category: "miscelaneos" },
  { id: 59, name: "Stitch Hawai", price: 600, image: "/images/stichhawai.png", available:true, category: "miscelaneos" },
  { id: 61, name: "Skate", price: 550, image: "/images/skate.png", available:true, category: "miscelaneos" },
  { id: 65, name: "Estampita Red", price: 600, image: "/images/red.png", available:true, category: "miscelaneos" },
  { id: 66, name: "Estampita Lemon", price: 600, image: "/images/postal.png", available:true, category: "miscelaneos" },
  { id: 67, name: "Police", price: 600, image: "/images/police.png", available:true, category: "miscelaneos" },
  { id: 68, name: "Ojos gato", price: 550, image: "/images/ojosgato.png", available:true, category: "miscelaneos" },
  { id: 85, name: "Nasa", price: 600, image: "/images/nasa.png", available:true, category: "miscelaneos" },
  { id: 86, name: "Moño", price: 500, image: "/images/moño.png", available:true, category: "miscelaneos" },
  { id: 87, name: "Miguel Angel", price: 550, image: "/images/miguelangel.png", available:true, category: "miscelaneos" },
  { id: 88, name: "Parental Advisory", price: 600, image: "/images/advisory.png", available:true, category: "miscelaneos" },
  { id: 92, name: "Banderitas", price: 550, image: "/images/banderitas.png", available:true, category: "miscelaneos" },
  { id: 101, name: "Bad Idea Right?", price: 600, image: "/images/badidearight.png", available:true, category: "miscelaneos" },
  { id: 114, name: "Camarita", price: 600, image: "/images/camarita.png", available:true, category: "miscelaneos" },
  { id: 126, name: "Lamparita", price: 600, image: "/images/lamparita.png", available:true, category: "miscelaneos" },
  { id: 127, name: "Luna Van Gogh", price: 600, image: "/images/lunavangogh.png", available:true, category: "miscelaneos" },
  { id: 133, name: "Route 66", price: 600, image: "/images/route66.png", available:true, category: "miscelaneos" },
  { id: 134, name: "Rusteze", price: 600, image: "/images/ruteze.png", available:false, category: "miscelaneos" },
  { id: 135, name: "Smile", price: 600, image: "/images/smile.png", available:true, category: "miscelaneos" },
  { id: 160, name: "Corazon Anatomico", price: 600, image: "/images/corazonrial.png", available:true, category: "miscelaneos" },
  { id: 161, name: "Good Vibes Gastado", price: 550, image: "/images/goodvibesgastado.png", available:true, category: "miscelaneos" },
  { id: 162, name: "Globo", price: 600, image: "/images/globoaero.png", available:true, category: "miscelaneos" },
  { id: 165, name: "222", price: 550, image: "/images/222.png", available:true, category: "miscelaneos" },
  { id: 169, name: "Camioneta", price: 600, image: "/images/camioneta.png", available:true, category: "miscelaneos" },

    // ===== BASKET ===== //
  { id: 84, name: "NBA", price: 600, image: "/images/nba.png", available:true, category: "basket" },
  { id: 132, name: "Denis Rodman", price: 600, image: "/images/rodman.png", available:true, category: "basket" },
  { id: 142, name: "Blue Label Elissir", price: 600, image: "/images/bluelabel.png", available:true, category: "basket" },
  { id: 146, name: "Stephen Curry", price: 550, image: "/images/curry3.png", available:true, category: "basket" },
  { id: 148, name: "Ginobili", price: 550, image: "/images/ginobili.png", available:true, category: "basket" },
  { id: 150, name: "Pelota Basquet", price: 600, image: "/images/pelotabasquet.png", available:true, category: "basket" },

  // ===== FORMULA 1 ===== //
  { id: 89, name: "F1 Ferrari", price: 500, image: "/images/autoferrari.png", available:true, category: "formula1" },
  { id: 90, name: "Estampita Colapinto", price: 600, image: "/images/estampitacolapinto.png", available:true, category: "formula1" },
  { id: 91, name: "Formula 1", price: 500, image: "/images/f1.png", available:true, category: "formula1" },
 
  { id: 117, name: "Colapinto 43", price: 500, image: "/images/colapinto43.png", available:true, category: "formula1" },


];


export default stickers;